[project]
name = "synchronicity"
version = "0.6.0"
description = "Export blocking and async library versions from a single async implementation"
readme = "README.md"

dependencies = [
    "sigtools==4.0.1",
    "typing_extensions>=4.6",
]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["synchronicity*"]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
