name: Check
on: push

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: uv sync --only-group=lint
      - name: Check lint with Ruff
        run: uv run --only-group=lint ruff check .
      - name: Check formatting with Ruff
        run: uv run --only-group=lint ruff format --diff .

  mypy:
    name: MyPy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: uv sync --only-group=lint
      - name: Run
        run: uv run --only-group=lint mypy src/synchronicity
